### ISSUE TITLE
Big molecules: GPU usage and getting first x results

### ISSUE THREAD

**Issue by dphilip** [StructureGenerator/surge#13]
Dear all, 
you have done great work on this package as I'm working on larger molecules (>20 carbon atoms) I would like to know if it is possible to:
1) take advantage of GPU in the calculations
2) receive the first 100 results, as an example of the structure generated. This would be particularly helpful when dealing with task to take to complete.
Take care and continue!

**Comment by MehmetAzizYirik** [comment]
Dear @dphilip 

Thanks for your feedback. I will address two questions together. surge has the output option called "-m" that helps users to split the generation process into independent sets. By that, user can generate small subset of the chemical space instead of generating the whole. This feature is useful for handling large molecules. Additionally, splitting the process using the -m option facilitates parallelisation, allowing users to leverage GPUs effectively.  Below is the screenshot for the -m option. For more details, please refer to the user manual. 

<img width="648" alt="outputOptions" src="https://github.com/StructureGenerator/surge/assets/15614358/c8e7ea95-6e9a-45cd-b438-5a73ed70879d">

**Comment by dphilip** [comment]
Thanks Mehmet, I am already trying it out! Is the package configured to take advantage of a GPU?

**Comment by MehmetAzizYirik** [comment]
> Thanks Mehmet, I am already trying it out! Is the package configured to take advantage of a GPU?

Besides that -m option's usage, the current version of surge does not have any specific configuration for GPU.

**Comment by dphilip** [comment]
Great, thanks for making this clear! Right now I am using a bold -m1/100, to get a response from an otherwise immense task. 
Thanks again!
