### ISSUE TITLE
Increasing the number of heavy atoms allowed

### ISSUE THREAD

**Issue by breisfeld** [StructureGenerator/surge#2]
Hi, 

Is there is a straight-forward way to increase the number of heavy atoms that surge allows?

For my application, I need to examine molecules with up to about 45 heavy atoms. 

Thank you.

**Comment by steinbeck** [comment]
Hi Brad, do you have any boundary conditions that make 45 heavy atoms feasible? Depending on the elemental composition and the degree of unsaturation, the combinatorial explosion strikes somewhere between 15 and 25 heavy atoms (handwaving numbers). 45 heavy atoms sounds unfeasible. 
Of course, if you just want to generate some candidates, that might even work. 

So, in this case, the surge manual has the answer at the bottom of page 15:

Surge can be compiled with -DWORDSIZE=64 if nautyW1.a is replaced by nautyL1.a.
That will raise the limit on the number of non-hydrogen atoms from 32 to 64, but there
are very few molecular formulas of that size for which the number of isomers is within
reason. The number of bonds, ignoring hydrogen, is limited in 64 in any case.

Cheers, Chris

**Comment by breisfeld** [comment]
Hi Chris, 

I understand.

My current interest is in enumerating short- and medium-chain chlorinated paraffins (SCCPs, MCCPs) with a given range of number of carbon number atoms and a certain percent chlorine. 

If there were a way to generate even a 'random' subset, that would be great. 

I have an ongoing need for this type of tool beyond SCCPs and MCCPs. I have to deal with complex chemical mixtures with some overall properties and my aim is to be able to generate a set of likely candidate molecules that could comprise the mixture.

Thank you for the comment about the manual. I didn't see that when I first scanned the document. I looked at the code, but wasn't sure if changing the wordsize would have unintended consequences.

Thanks!

Kind regards,
Brad

**Comment by steinbeck** [comment]
Excellent. A "random" subset might be tricky, but since surge starts outputting structures right away, can just record the initial output. Also, using the -m#/# option would give you structures from different portions of the space. 
Let me know if compiling surge with  -DWORDSIZE=64 works for you. 
Kind regards, Chris

**Comment by breisfeld** [comment]
I will give those suggestions a try. Thanks!

Kind regards,
Brad

**Comment by steinbeck** [comment]
Here is another remark from Brendan on the problem:

Basically, the entire computation has the shape of a tree, with the output
molecules being the leaves of the tree.  If a probability is associated with
each edge of the tree, so that the edge is only followed with that probability,
then a random set of leaves remain.

It is a complex question to say what the distribution of the output looks
like. Certainly, it will not be true that every isomer has the same probability
of being output, but there can be a useful approximation of that.

As a first approximation, users can write plugins for each stage that reject
with high probability.  That will give less clustered results than -m gives.

**Comment by breisfeld** [comment]
That makes sense. I am not a C programmer, so I don't know if I can create such a plugin, but I'll take a look at the examples.
